### PR TITLE
Redirect to new status page

### PR DESCRIPTION
**Pull request by WillNilges**
Moves old status page content to `/status-page-old`, and creates a 302 at `/status-page`.

### CODE REVIEW

**Review by andybaumgar — CHANGES_REQUESTED** [review]
Looks good.  I think we should change the status banner on the home page to go to status.nycmesh.net as well. (And use that domain outside this pr).  https://www.nycmesh.net/

**Comment by andybaumgar** [comment]
image

**Comment by WillNilges** [comment]
OK, then do it.

**Comment by WillNilges** [comment]
> I think we should change the status banner on the home page to go to status.nycmesh.net as well.

It does. The banner 302s you.

**Comment by WillNilges** [comment]
As for the domain change, I have no idea how to do that or who would do that.

**Comment by andybaumgar** [comment]
> > I think we should change the status banner on the home page to go to status.nycmesh.net as well.
> 
> It does. The banner 302s you.

My gut feeling is that we should minimize 302 usage to redirecting, not "directing".  I.e. we should update the actual website to point to the actual location, but then add redirection so the old links continue to work.

**Comment by andybaumgar** [comment]
Anyways, I am happy to take over the PR if you want.

**Pull request merged**
